### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by maartenheideman** [FrameworkSystemsGmbH/capacitor-plugin-webview-cache#1]
I'll get this build errors on android after adding this plugin:

`/node_modules/capacitor-plugin-webview-cache/android/src/main/java/com/fs/htmlclient/plugins/webviewcache/ClearCache.java:3: error: package android.webkit does not exist
import android.webkit.WebView;`

`/node_modules/capacitor-plugin-webview-cache/android/src/main/java/com/fs/htmlclient/plugins/webviewcache/ClearCache.java:7: error: cannot find symbol
    private WebView webView;
            ^
  symbol:   class WebView
  location: class ClearCache`

The compile and target SDK are set to 31, using capacitor 3.4.3

**Comment by FSDRE** [comment]
If android.webkit cannot be imported you probably are missing a project/sdk reference. The error is not introduced by this plugin.
