### ISSUE TITLE
Capacitor 5 Support

### ISSUE THREAD

**Issue by seikosantana** [FrameworkSystemsGmbH/capacitor-plugin-webview-cache#2]
Hi, I tried running migration on my project and it shows that this plugin does not support capacitor 5. Will the plugin be updated to support capacitor 5? Thanks in advance

**Comment by FSDRE** [comment]
Sure thing. Be aware that this repo is owned by a company and therefor updates are delayed as long as the company itself does not upgrade to Capacitor 5. But it will happen in the next couple of weeks.

**Comment by FSDRE** [comment]
Done
